spring:
  application:
    name: messaging-emulator
<<<<<<< HEAD
  #config:
  #  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
=======
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  sql:
    init:
      mode: always
      platform: hsqldb
server:
  port: 8080
>>>>>>> 6e3198fbc6cb0628b0a8e9deaddadc31547cf178
